version: '3.9'

services:
  db:
    container_name: db
    image: 'postgres:17.0-alpine'
    restart: always
    networks:
      - scg_network
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 10M
  localstack-sqs:
    container_name: localstack-sqs
    image: localstack/localstack:2.0
    platform: linux/amd64
    restart: always
    networks:
      - scg_network
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ${SQS_REGION}
      EDGE_PORT: 4566
      SERVICES: sqs
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - 'localstack-data:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  scg_network:

volumes:
  postgres-data:
  localstack-data:
  cache:
    driver: local