version: '3.9'

services:
  db:
    container_name: db
    image: 'postgres:17.0-alpine'
    restart: always
    networks:
      - scg_network
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 10M

networks:
  scg_network:

volumes:
  postgres-data:
  cache:
    driver: local
