import type { Config } from '@jest/types';

export default {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.(spec|e2e-spec)\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '<rootDir>/src/**',
    '!<rootDir>/src/**/*.module.ts',
    '!<rootDir>/src/**/*.dto.ts',
    '!<rootDir>/src/**/*.config.ts',
    '!<rootDir>/src/**/*.constants.ts',
    '!<rootDir>/src/**/main.ts',
    '!<rootDir>/src/**/*.entity.ts',
    '!<rootDir>/src/**/*.exception.ts',
    '!<rootDir>/test/config.test.ts',
    '!<rootDir>/src/entity-subscriber/subscriber/*.subscriber.ts',
    '!<rootDir>/src/schedule/command/*',
    '!<rootDir>/src/migrations/**',
    '!<rootDir>/src/schema-elasticsearch/**',
    '!<rootDir>/src/auth/jwt-auth.guard.ts',
    '!<rootDir>/src/auth/**',
    '!<rootDir>/src/common/**',
    '!<rootDir>/src/health/*',
    '!<rootDir>/src/logger/*',
    '!<rootDir>/src/**/*.controller.test.ts',
    '!<rootDir>/src/**/interfaces/*',
    '!<rootDir>/src/**/common/gateways/*',
    '!<rootDir>/src/**/common/types/*',
  ],
  coverageDirectory: 'test/coverage',
  testEnvironment: 'node',
  preset: 'ts-jest',
  testResultsProcessor: 'jest-sonar-reporter',
  coverageProvider: 'v8',
  maxWorkers: 3,
  testTimeout: 1200000,
} as Config.InitialOptions;
