name: Test

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  run-test:
    name: Run test build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run test build
        run: yarn run build
